INSERT INTO teacher 
    VALUES (
    NULL,
    'TANVIR',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    2059
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'ALICIA',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5611
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'GWEN',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5691
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'JOYCE',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5682
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'THEODOR',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5540
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'ZAMAN',
    NULL,
    NULL,
    NULL,
    'assistant',
    DEFAULT,
    2059
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'ALICE',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5611
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'GWENOLIN',
    NULL,
    NULL,
    NULL,
    'junior',
    DEFAULT,
    5691
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'JOYCEER',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5682
    );
INSERT INTO teacher 
    VALUES (
    NULL,
    'THEODOR',
    NULL,
    NULL,
    NULL,
    'senior',
    DEFAULT,
    5540
    );
    