INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL,
    15,
    'TANVIR#11',
    DEFAULT,
    'HI NICE TO MEET YOU ALL.',
    SYSDATE,
    DEFAULT
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL,
    5,
    'TANVIR#11',
    'HELP POST',
    'CAN ANYONE PROVIDE ME WITH NEW CLASS ROUTINE',
    SYSDATE,
    DEFAULT
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL,
    1, 
    'TANVIR#11', 
    'POST', 
    'START PREPARING FOR THE UPCOMING EXAM', 
    TO_DATE('1/10/2002', 'MM/DD/YYYY'), 
    0
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    12, 
    'ALICIA#12', 
    'POST', 
    'PLEASE BRING YOUR TEXT BOOK IN THE CLASS', 
    TO_DATE('9/23/2008', 'MM/DD/YYYY'), 
    0
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    7, 
    'TONY STARK_3', 
    'POST', 
    'HI FRIENDS!LOOKS LIKE WE MADE SOME PROGRESS IN THIS PROJECT.', 
    TO_DATE('4/23/2012', 'MM/DD/YYYY'), 
    0);
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    9, 
    'TANVIR_55',
    'POST', 
    'WHAT IS THE TIME OF NEXT CLASS TEST OF ENGLISH', 
    TO_DATE('4/19/2038', 'MM/DD/YYYY'), 
    0
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    2, 
    'ALICIA_86', 
    'HELP POST', 
    'CAN ANYONE HELP ME IN MATH CHAPTER 2', 
    TO_DATE('7/16/2039', 'MM/DD/YYYY'), 
    0
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    9, 
    'ALICIA_86', 
    'HELP POST', 
    'CAN ANYONE HELP ME WITH MY PROGRAMMING PROJECT', 
    TO_DATE('6/7/2011', 'MM/DD/YYYY'), 
    0
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    9, 
    'GLAMORA_15', 
    'POST', 
    'GOOD MORNING FRIENDS.', 
    TO_DATE('8/3/2014', 'MM/DD/YYYY'), 
    0
    );
INSERT INTO newsfeed
    VALUES(
    newsfeed_seq.NEXTVAL, 
    18,
    'ALICIA#12', 
    'POST', 
    'THOSE WHO ARE ABSENT IN THE RECECNT CLASSES PLEASE CONTACT ME AT 3:00', 
    TO_DATE('11/7/2016', 'MM/DD/YYYY'), 
    0
    );
