INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    2,
    2,
    'wELCOME', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    11,
    15,
    'NICE TO MEET YOU TOO', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    14,
    12,
    'YES TEACHER WE WILL', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    14,
    12,
    'OK :)', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    6,
    6,
    'WELCOME HERE', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    9,
    9,
    'WELCOME', 
    '8-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    14,
    14,
    'WELCOME TEACHER', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    29,
    9,
    'GOOD MORNING', 
    '3-JULY-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    2,
    2,
    'REF', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    2,
    2,
    'WELCOME HERE', 
    '3-JUNE-2022',
    NULL
    );
INSERT INTO newsfeed_comment
    VALUES(
    newsfeed_comment_seq.NEXTVAL,
    24,
    2,
    'WELCOME HERE AGAIN', 
    '3-JUNE-2022',
    NULL
    );

