INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    1,
    2,
    'HOWDY DEAR',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    2,
    1,
    'I AM FINE AND YOU',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    1,
    2,
    'SAME TO YOU. CAN YOU HELP ME IN A WORK',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    1,
    2,
    'I LOST MY PEN IN THE CLASS SAIF,TONOY AND ASHIK SAID THAT YOU MIGHT HAVE IT.',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    2,
    1,
    'YES I HAD IT BUT I GAVE IT TO THE STUDENT LOST AND FOUND OFFICE. SO YOU HAVE TO COLLECT IT FROM THERE.',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    1,
    2,
    'OK I WILL .THANK FOR THE HELP.THANKS A LOT.',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    2,
    1,
    'YOUR WELCOME',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    1,
    2,
    'OK BYE/',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    2,
    1,
    'GOOD LUCK',
    SYSDATE
    );
INSERT INTO message
    VALUES(
    message_seq.NEXTVAL,
    1,
    2,
    'THANKS AGAIN',
    SYSDATE
    );
