/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package classroom_management_system;

import classroom_management_system.main.student;
import classroom_management_system.main.teacher;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanvir Zaman
 */
public class login_registration extends javax.swing.JFrame {

    /** Creates new form cms_main_frame */
    public login_registration() {
        initComponents();
        this.setLocationRelativeTo(null);
        login_title.setText((String)type_selection.getSelectedItem()+" LOGIN");
        login_title1.setText((String)type_selection.getSelectedItem()+" REGISTRATION");
        student_registration.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        minimized = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        login_body = new javax.swing.JPanel();
        username_login = new javax.swing.JLabel();
        password_login = new javax.swing.JLabel();
        login_header = new javax.swing.JPanel();
        login_title = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        type_selection = new javax.swing.JComboBox<>();
        about_me = new javax.swing.JPanel();
        about_tanvir = new javax.swing.JPanel();
        login_title3 = new javax.swing.JLabel();
        my_name = new javax.swing.JLabel();
        my_id = new javax.swing.JLabel();
        my_project = new javax.swing.JLabel();
        github_account_link = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        github_account_link1 = new javax.swing.JLabel();
        REGISTRATION = new javax.swing.JPanel();
        login_header1 = new javax.swing.JPanel();
        login_title1 = new javax.swing.JLabel();
        information = new javax.swing.JPanel();
        teacher_registration = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        teacher_address_label = new javax.swing.JLabel();
        teacher_subject_lable = new javax.swing.JLabel();
        teacher_address = new javax.swing.JTextField();
        first_name = new javax.swing.JTextField();
        teacher_role_label = new javax.swing.JLabel();
        last_name_label = new javax.swing.JTextField();
        teacher_code = new javax.swing.JPasswordField();
        role = new javax.swing.JTextField();
        teacher_code_lebel = new javax.swing.JLabel();
        teacher_subject = new javax.swing.JTextField();
        teacher_name = new javax.swing.JTextField();
        teacher_name_lebel = new javax.swing.JLabel();
        teacher_password_lebel = new javax.swing.JLabel();
        teacher_first_name_lebel = new javax.swing.JLabel();
        teacher_confirm_password_lebel = new javax.swing.JLabel();
        teacher_last_name_lebel = new javax.swing.JLabel();
        teacher_password = new javax.swing.JTextField();
        teacher_confirm_password = new javax.swing.JTextField();
        student_registration = new javax.swing.JPanel();
        student_last_name_lebel = new javax.swing.JLabel();
        student_last_name = new javax.swing.JTextField();
        student_register = new javax.swing.JButton();
        student_name = new javax.swing.JTextField();
        student_address_lebel = new javax.swing.JLabel();
        student_name_label = new javax.swing.JLabel();
        student_address = new javax.swing.JTextField();
        student_first_name_label = new javax.swing.JLabel();
        student_first_name = new javax.swing.JTextField();
        student_father_name_label = new javax.swing.JLabel();
        student_mother_name_lable = new javax.swing.JLabel();
        student_roll_label = new javax.swing.JLabel();
        student_roll = new javax.swing.JTextField();
        student_class = new javax.swing.JTextField();
        student_class_label = new javax.swing.JLabel();
        student_year = new javax.swing.JTextField();
        student_year_label = new javax.swing.JLabel();
        student_father_name = new javax.swing.JTextField();
        student_mother_name = new javax.swing.JTextField();
        student_password_label = new javax.swing.JLabel();
        student_confirm_password_label = new javax.swing.JLabel();
        student_password = new javax.swing.JPasswordField();
        student_confirm_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(231, 86, 106));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(107, 98, 185));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 1, true));
        jPanel1.setForeground(new java.awt.Color(135, 189, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Classroom Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 370, 40));

        jPanel5.setBackground(new java.awt.Color(84, 84, 84));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 1, true));

        minimized.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minimized.setForeground(new java.awt.Color(255, 255, 255));
        minimized.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimized.setText("__");
        minimized.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedMouseClicked(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("X");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimized, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimized))
                .addGap(7, 7, 7))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 70, 30));

        jPanel2.setBackground(new java.awt.Color(40, 34, 63));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_body.setBackground(new java.awt.Color(107, 98, 185));
        login_body.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 1, true));

        username_login.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        username_login.setForeground(new java.awt.Color(0, 255, 204));
        username_login.setText("Username");

        password_login.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        password_login.setForeground(new java.awt.Color(0, 255, 204));
        password_login.setText("Password");

        login_header.setBackground(new java.awt.Color(40, 34, 63));

        login_title.setBackground(new java.awt.Color(40, 34, 63));
        login_title.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        login_title.setForeground(new java.awt.Color(107, 98, 185));
        login_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title.setText("LOGIN");

        javax.swing.GroupLayout login_headerLayout = new javax.swing.GroupLayout(login_header);
        login_header.setLayout(login_headerLayout);
        login_headerLayout.setHorizontalGroup(
            login_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        login_headerLayout.setVerticalGroup(
            login_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_title)
                .addContainerGap())
        );

        login.setBackground(new java.awt.Color(51, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        type_selection.setForeground(new java.awt.Color(255, 51, 51));
        type_selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEACHER", "STUDENT", "ADMIN" }));
        type_selection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        type_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_selectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_bodyLayout = new javax.swing.GroupLayout(login_body);
        login_body.setLayout(login_bodyLayout);
        login_bodyLayout.setHorizontalGroup(
            login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(login_bodyLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_login)
                    .addComponent(password_login))
                .addGap(18, 18, 18)
                .addGroup(login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addGroup(login_bodyLayout.createSequentialGroup()
                        .addComponent(login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(type_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(password))
                .addContainerGap())
        );
        login_bodyLayout.setVerticalGroup(
            login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_bodyLayout.createSequentialGroup()
                .addComponent(login_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_login)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_login)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(login_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(type_selection))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(login_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 170));

        about_me.setBackground(new java.awt.Color(107, 98, 185));
        about_me.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 1, true));

        about_tanvir.setBackground(new java.awt.Color(40, 34, 63));

        login_title3.setBackground(new java.awt.Color(40, 34, 63));
        login_title3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        login_title3.setForeground(new java.awt.Color(107, 98, 185));
        login_title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title3.setText("ABOUT ME");

        javax.swing.GroupLayout about_tanvirLayout = new javax.swing.GroupLayout(about_tanvir);
        about_tanvir.setLayout(about_tanvirLayout);
        about_tanvirLayout.setHorizontalGroup(
            about_tanvirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(about_tanvirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_title3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        about_tanvirLayout.setVerticalGroup(
            about_tanvirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, about_tanvirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_title3)
                .addContainerGap())
        );

        my_name.setForeground(new java.awt.Color(0, 255, 255));
        my_name.setText("Name    : MD.Kamruzzaman Tanvir");

        my_id.setForeground(new java.awt.Color(0, 255, 255));
        my_id.setText("ID           : 201400059");

        my_project.setForeground(new java.awt.Color(0, 255, 255));
        my_project.setText("Project  : CLASSROOM_MANAGEMENT_SYSTEM  ");

        github_account_link.setForeground(new java.awt.Color(0, 255, 255));
        github_account_link.setText("GitHub  : KZTanvir");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classroom_management_system/df.jpg"))); // NOI18N

        github_account_link1.setForeground(new java.awt.Color(0, 255, 255));
        github_account_link1.setText("Course : Database Management System");

        javax.swing.GroupLayout about_meLayout = new javax.swing.GroupLayout(about_me);
        about_me.setLayout(about_meLayout);
        about_meLayout.setHorizontalGroup(
            about_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(about_tanvir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(about_meLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(about_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(about_meLayout.createSequentialGroup()
                        .addComponent(my_project)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(about_meLayout.createSequentialGroup()
                        .addGroup(about_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(my_name)
                            .addComponent(my_id)
                            .addComponent(github_account_link))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30))
                    .addGroup(about_meLayout.createSequentialGroup()
                        .addComponent(github_account_link1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        about_meLayout.setVerticalGroup(
            about_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, about_meLayout.createSequentialGroup()
                .addComponent(about_tanvir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(about_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(about_meLayout.createSequentialGroup()
                        .addComponent(my_name)
                        .addGap(12, 12, 12)
                        .addComponent(my_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(github_account_link)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(my_project)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(github_account_link1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(about_me, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 340, 200));

        REGISTRATION.setBackground(new java.awt.Color(107, 98, 185));
        REGISTRATION.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        REGISTRATION.setMinimumSize(new java.awt.Dimension(0, 0));
        REGISTRATION.setPreferredSize(new java.awt.Dimension(420, 380));

        login_header1.setBackground(new java.awt.Color(40, 34, 63));

        login_title1.setBackground(new java.awt.Color(40, 34, 63));
        login_title1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        login_title1.setForeground(new java.awt.Color(107, 98, 185));
        login_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_title1.setText("REGISTRATION");

        javax.swing.GroupLayout login_header1Layout = new javax.swing.GroupLayout(login_header1);
        login_header1.setLayout(login_header1Layout);
        login_header1Layout.setHorizontalGroup(
            login_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_title1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        login_header1Layout.setVerticalGroup(
            login_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_header1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_title1)
                .addContainerGap())
        );

        information.setBackground(new java.awt.Color(107, 98, 185));

        teacher_registration.setBackground(new java.awt.Color(107, 98, 185));

        register.setBackground(new java.awt.Color(102, 255, 255));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        teacher_address_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_address_label.setForeground(new java.awt.Color(0, 255, 204));
        teacher_address_label.setText("Address");

        teacher_subject_lable.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_subject_lable.setForeground(new java.awt.Color(0, 255, 204));
        teacher_subject_lable.setText("Subject");

        teacher_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_addressActionPerformed(evt);
            }
        });

        teacher_role_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_role_label.setForeground(new java.awt.Color(0, 255, 204));
        teacher_role_label.setText("Role");

        teacher_code.setText("0");
        teacher_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_codeActionPerformed(evt);
            }
        });

        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        teacher_code_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_code_lebel.setForeground(new java.awt.Color(0, 255, 204));
        teacher_code_lebel.setText("Teacher Code");

        teacher_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_subjectActionPerformed(evt);
            }
        });

        teacher_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_nameActionPerformed(evt);
            }
        });

        teacher_name_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_name_lebel.setForeground(new java.awt.Color(0, 255, 204));
        teacher_name_lebel.setText("Teacher Name");

        teacher_password_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_password_lebel.setForeground(new java.awt.Color(0, 255, 204));
        teacher_password_lebel.setText("Password");

        teacher_first_name_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_first_name_lebel.setForeground(new java.awt.Color(0, 255, 204));
        teacher_first_name_lebel.setText("First Name");

        teacher_confirm_password_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_confirm_password_lebel.setForeground(new java.awt.Color(0, 255, 204));
        teacher_confirm_password_lebel.setText("Confirm Password");

        teacher_last_name_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        teacher_last_name_lebel.setForeground(new java.awt.Color(0, 255, 204));
        teacher_last_name_lebel.setText("Last Name");

        teacher_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacher_registrationLayout = new javax.swing.GroupLayout(teacher_registration);
        teacher_registration.setLayout(teacher_registrationLayout);
        teacher_registrationLayout.setHorizontalGroup(
            teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacher_registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacher_registrationLayout.createSequentialGroup()
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teacher_address_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teacher_last_name_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teacher_first_name_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teacher_name_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacher_name)
                            .addComponent(teacher_address)
                            .addComponent(first_name)
                            .addComponent(last_name_label)))
                    .addGroup(teacher_registrationLayout.createSequentialGroup()
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(teacher_subject_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(teacher_role_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(role)
                            .addComponent(teacher_subject)))
                    .addGroup(teacher_registrationLayout.createSequentialGroup()
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(teacher_registrationLayout.createSequentialGroup()
                                .addComponent(teacher_confirm_password_lebel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(teacher_registrationLayout.createSequentialGroup()
                                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(teacher_password_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teacher_code_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(3, 3, 3)))
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(teacher_registrationLayout.createSequentialGroup()
                                .addComponent(register)
                                .addGap(0, 191, Short.MAX_VALUE))
                            .addGroup(teacher_registrationLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacher_confirm_password, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(teacher_password, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(teacher_code, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        teacher_registrationLayout.setVerticalGroup(
            teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacher_registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacher_registrationLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacher_first_name_lebel)
                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teacher_name_lebel)
                        .addComponent(teacher_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_last_name_lebel)
                    .addComponent(last_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_address_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_role_label)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_subject_lable)
                    .addComponent(teacher_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_code_lebel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_password_lebel)
                    .addComponent(teacher_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacher_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacher_confirm_password_lebel)
                    .addComponent(teacher_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        student_registration.setBackground(new java.awt.Color(107, 98, 185));

        student_last_name_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_last_name_lebel.setForeground(new java.awt.Color(0, 255, 204));
        student_last_name_lebel.setText("Last Name");

        student_register.setBackground(new java.awt.Color(102, 255, 255));
        student_register.setText("REGISTER");
        student_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_registerActionPerformed(evt);
            }
        });

        student_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_nameActionPerformed(evt);
            }
        });

        student_address_lebel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_address_lebel.setForeground(new java.awt.Color(0, 255, 204));
        student_address_lebel.setText("Address");

        student_name_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_name_label.setForeground(new java.awt.Color(0, 255, 204));
        student_name_label.setText("Student Name");

        student_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_addressActionPerformed(evt);
            }
        });

        student_first_name_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_first_name_label.setForeground(new java.awt.Color(0, 255, 204));
        student_first_name_label.setText("First Name");

        student_father_name_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_father_name_label.setForeground(new java.awt.Color(0, 255, 204));
        student_father_name_label.setText("Father Name");

        student_mother_name_lable.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_mother_name_lable.setForeground(new java.awt.Color(0, 255, 204));
        student_mother_name_lable.setText("Mother Name");

        student_roll_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_roll_label.setForeground(new java.awt.Color(0, 255, 204));
        student_roll_label.setText("Roll");

        student_class_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_class_label.setForeground(new java.awt.Color(0, 255, 204));
        student_class_label.setText("Class");

        student_year_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_year_label.setForeground(new java.awt.Color(0, 255, 204));
        student_year_label.setText("Year");

        student_password_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_password_label.setForeground(new java.awt.Color(0, 255, 204));
        student_password_label.setText("Password");

        student_confirm_password_label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        student_confirm_password_label.setForeground(new java.awt.Color(0, 255, 204));
        student_confirm_password_label.setText("Confirm Password");

        javax.swing.GroupLayout student_registrationLayout = new javax.swing.GroupLayout(student_registration);
        student_registration.setLayout(student_registrationLayout);
        student_registrationLayout.setHorizontalGroup(
            student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student_registrationLayout.createSequentialGroup()
                        .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(student_mother_name_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_father_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_address_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_last_name_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_first_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addGroup(student_registrationLayout.createSequentialGroup()
                                .addComponent(student_roll_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(student_roll)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student_name)
                            .addComponent(student_address)
                            .addComponent(student_first_name)
                            .addComponent(student_last_name)
                            .addComponent(student_father_name)
                            .addComponent(student_mother_name)
                            .addGroup(student_registrationLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(student_class_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(student_class, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(student_year_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(student_year, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))))
                    .addGroup(student_registrationLayout.createSequentialGroup()
                        .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(student_confirm_password_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(student_registrationLayout.createSequentialGroup()
                                .addComponent(student_register)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(student_password)
                            .addComponent(student_confirm_password))))
                .addContainerGap())
        );
        student_registrationLayout.setVerticalGroup(
            student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student_registrationLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(student_first_name_label))
                    .addGroup(student_registrationLayout.createSequentialGroup()
                        .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(student_name_label)
                            .addComponent(student_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(student_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_last_name_lebel)
                    .addComponent(student_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_father_name_label)
                    .addComponent(student_father_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_mother_name_lable)
                    .addComponent(student_mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_address_lebel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_roll_label)
                    .addComponent(student_roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_year_label)
                    .addComponent(student_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_class_label)
                    .addComponent(student_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student_registrationLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(student_confirm_password_label)
                            .addComponent(student_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(student_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(student_password_label)
                        .addComponent(student_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(student_register)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout informationLayout = new javax.swing.GroupLayout(information);
        information.setLayout(informationLayout);
        informationLayout.setHorizontalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teacher_registration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(student_registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informationLayout.setVerticalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(informationLayout.createSequentialGroup()
                    .addComponent(teacher_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
            .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(informationLayout.createSequentialGroup()
                    .addComponent(student_registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout REGISTRATIONLayout = new javax.swing.GroupLayout(REGISTRATION);
        REGISTRATION.setLayout(REGISTRATIONLayout);
        REGISTRATIONLayout.setHorizontalGroup(
            REGISTRATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        REGISTRATIONLayout.setVerticalGroup(
            REGISTRATIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRATIONLayout.createSequentialGroup()
                .addComponent(login_header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(REGISTRATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String user = username.getText();
        String pass = password.getText();
        String role = (String)type_selection.getSelectedItem();
        int status;
        try{
            if("STUDENT".equals(role)){
                student student = new student();
                status = student.login(user, pass);
                if(status==1){
                    //teacher_home home = new teacher_home();
                    //home.show();
                    dispose();
                    JOptionPane.showMessageDialog(this, student.login_status);
                }else JOptionPane.showMessageDialog(this, student.login_status);
            }else if("TEACHER".equals(role)){
                teacher teacher = new teacher();
                status = teacher.login(user, pass);
                if(status==1){
                    //teacher_home home = new teacher_home();
                    //home.teacher_home(user, pass, teacher.id, role);
                    //home.show();
                    dispose();
                    JOptionPane.showMessageDialog(this, teacher.login_status);
                }else JOptionPane.showMessageDialog(this, teacher.login_status);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void type_selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_selectionActionPerformed
        // TODO add your handling code here:
        login_title.setText((String)type_selection.getSelectedItem()+" LOGIN");
        if(((String)type_selection.getSelectedItem()).equals("STUDENT")){
            student_registration.setVisible(true);
            teacher_registration.setVisible(false);
        }else{
            student_registration.setVisible(false);
            teacher_registration.setVisible(true);
        }
        login_title1.setText((String)type_selection.getSelectedItem()+" REGISTRATION");
    }//GEN-LAST:event_type_selectionActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelMouseClicked

    private void minimizedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizedMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        teacher teacher= new teacher();
        String t_name = teacher_name.getText();
        String t_first_name = first_name.getText();
        String t_last_name = last_name_label.getText();
        String t_address = teacher_address.getText();
        String t_role = role.getText();
        String t_subject = teacher_subject.getText();
        int t_code = Integer.parseInt(teacher_code.getText());
        String t_password = teacher_password.getText();
        String t_confirm_password = teacher_confirm_password.getText();
        int status = teacher.registration(t_name, t_first_name, t_last_name, t_address, t_role, t_subject, t_code, t_password, t_confirm_password);
        if(status == 1){
            //cms_main_frame main = new cms_main_frame();
            //main.show();
            dispose();
            JOptionPane.showMessageDialog(this, teacher.registration_status);
        }else{
            JOptionPane.showMessageDialog(this, teacher.registration_status);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void teacher_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_addressActionPerformed

    private void teacher_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_codeActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void teacher_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_nameActionPerformed

    private void teacher_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_passwordActionPerformed

    private void student_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_registerActionPerformed
        // TODO add your handling code here:
        student student = new student();
        String name = student_name.getText();
        String first_name = student_first_name.getText();
        String last_name = student_last_name.getText();
        String father_name = student_father_name.getText();
        String mother_name = student_mother_name.getText();
        String address = student_address.getText();
        int roll = Integer.parseInt(student_roll.getText());
        int Class = Integer.parseInt(student_class.getText());
        int year = Integer.parseInt(student_year.getText());
        int status = student.registration(name, first_name, last_name, father_name, mother_name, address, roll, Class, year, student_password.getText(), student_confirm_password.getText());
        if(status == 1){
            //cms_main_frame main = new cms_main_frame();
            //main.show();
            dispose();
            JOptionPane.showMessageDialog(this, student.registration_status);
        }else{
            JOptionPane.showMessageDialog(this, student.registration_status);
        }
        
    }//GEN-LAST:event_student_registerActionPerformed

    private void student_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_nameActionPerformed

    private void student_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_addressActionPerformed

    private void teacher_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_subjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel REGISTRATION;
    private javax.swing.JPanel about_me;
    private javax.swing.JPanel about_tanvir;
    private javax.swing.JLabel cancel;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel github_account_link;
    private javax.swing.JLabel github_account_link1;
    private javax.swing.JPanel information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField last_name_label;
    private javax.swing.JButton login;
    private javax.swing.JPanel login_body;
    private javax.swing.JPanel login_header;
    private javax.swing.JPanel login_header1;
    private javax.swing.JLabel login_title;
    private javax.swing.JLabel login_title1;
    private javax.swing.JLabel login_title3;
    private javax.swing.JLabel minimized;
    private javax.swing.JLabel my_id;
    private javax.swing.JLabel my_name;
    private javax.swing.JLabel my_project;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_login;
    private javax.swing.JButton register;
    private javax.swing.JTextField role;
    private javax.swing.JTextField student_address;
    private javax.swing.JLabel student_address_lebel;
    private javax.swing.JTextField student_class;
    private javax.swing.JLabel student_class_label;
    private javax.swing.JPasswordField student_confirm_password;
    private javax.swing.JLabel student_confirm_password_label;
    private javax.swing.JTextField student_father_name;
    private javax.swing.JLabel student_father_name_label;
    private javax.swing.JTextField student_first_name;
    private javax.swing.JLabel student_first_name_label;
    private javax.swing.JTextField student_last_name;
    private javax.swing.JLabel student_last_name_lebel;
    private javax.swing.JTextField student_mother_name;
    private javax.swing.JLabel student_mother_name_lable;
    private javax.swing.JTextField student_name;
    private javax.swing.JLabel student_name_label;
    private javax.swing.JPasswordField student_password;
    private javax.swing.JLabel student_password_label;
    private javax.swing.JButton student_register;
    private javax.swing.JPanel student_registration;
    private javax.swing.JTextField student_roll;
    private javax.swing.JLabel student_roll_label;
    private javax.swing.JTextField student_year;
    private javax.swing.JLabel student_year_label;
    private javax.swing.JTextField teacher_address;
    private javax.swing.JLabel teacher_address_label;
    private javax.swing.JPasswordField teacher_code;
    private javax.swing.JLabel teacher_code_lebel;
    private javax.swing.JTextField teacher_confirm_password;
    private javax.swing.JLabel teacher_confirm_password_lebel;
    private javax.swing.JLabel teacher_first_name_lebel;
    private javax.swing.JLabel teacher_last_name_lebel;
    private javax.swing.JTextField teacher_name;
    private javax.swing.JLabel teacher_name_lebel;
    private javax.swing.JTextField teacher_password;
    private javax.swing.JLabel teacher_password_lebel;
    private javax.swing.JPanel teacher_registration;
    private javax.swing.JLabel teacher_role_label;
    private javax.swing.JTextField teacher_subject;
    private javax.swing.JLabel teacher_subject_lable;
    private javax.swing.JComboBox<String> type_selection;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_login;
    // End of variables declaration//GEN-END:variables

}
